services:
  api:
    build:
      context: ../../services/api
    container_name: sap_api_dev
    ports:
      - "8000:8000"
    volumes:
      - ../../services/api/app:/app/app
    restart: unless-stopped
